site_name: CSP
theme: cinder
extra_css:
    - css/tablefont.css
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - admonition
    - pymdownx.arithmatex
    - pymdownx.details
nav:
    - Home: index.md
    - Course Notes: notes.md
    - Problem Sets:
        - 'Problem Set 1: helloworld': pset01.md
        - 'Problem Set 2: fahrenheit': pset02.md
    - Labs:
        - 'Lab 1: Digital Explosion': lab01.md
    - Quizzes: quizzes.md
    - Tests: tests.md
    - References: references.md
    - Syllabus: syllabus.md
