site_name: CSP
theme: cinder
extra_css:
    - css/tablefont.css
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - admonition
    - pymdownx.arithmatex
    - pymdownx.details
nav:
- Home: index.md
- Problem Sets:
    - 'Problem Set 1: Hello World': pset01.md
    - 'Problem Set 2: Fahrenheit': pset02.md
    - 'Problem Set 3: Note Frequency': pset03.md
    - 'Problem Set 4: Quarterback Rating': pset04.md
    - 'Problem Set 5: Water Meter': pset05.md
    - 'Problem Set 6: Vending Machine': pset06.md
    - 'Problem Set 7: Down Payment': pset07.md
    - 'Problem Set 8: Book Identifier': pset08.md
    - 'Problem Set 9: Radiation Exposure': pset09.md
    - 'Problem Set 10: Credit Card': pset10.md
    - 'Problem Set 11: Vigenere Cipher': pset11.md
- Labs:
    - 'Lab 1: Digital Explosion': lab01.md
    - 'Lab 2: Easter Sunday': lab02.md
    - 'Lab 3: Movie Critic': lab03.md
    - 'Lab 4: Coin Change': lab04.md
    - 'Lab 5: Gene Detection': lab05.md
    - 'Lab 6: Smooth Signal': lab06.md
    - 'Lab 7: Caesar Cipher': lab07.md
    - 'Lab 8: Polybius Cipher': lab08.md
    - 'Lab 9: Substitution Cipher': lab09.md
    - 'Lab 10: Request Line': lab10.md
- Tasks:
    - 'Explore Task': explore.md
    - 'Create Task': create.md
- Course Notes: notes.md
- Prior Tests: priortests.md
- References: references.md
- Syllabus: syllabus.md
